clone_folder: c:\project\dashboard_pi
shallow_clone: true
image:
- Visual Studio 2015

platform: 
# - x64
- Win32

configuration: Release
test: OFF

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'

  # sent environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets-3.1.2
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - set wxWidgets_LIBRARIES=%wxWidgets_LIB_DIR%
  - set wxWidgets_INCLUDE_DIRS=%WXWIN%\include
  - cmd: SET PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;

  # install dependencies:
  - choco install poedit nsis -x86

  # Download and unzip wxwidgets
  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/wxWidgets-3.1.2.7z
  - cmd: 7z x wxwidgets-3.1.2.7z -o%WXWIN% > null

  # some debugging information
  - set
  # - cmake --help

  # build wxWidgets (see above, not source code package but precompiled)
#  - cmd: cd %WXWIN%\build\msw\
#  - cmd: nmake -f makefile.vc BUILD=release SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_
#  - cmd: nmake -f makefile.vc BUILD=debug SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_

before_build:
  - cd c:\project\dashboard_pi
  - mkdir build
  - cd build
  - ps: Start-FileDownload https://github.com/canne/dashboard_pi/releases/download/0.0.1/opencpn.lib
#  - ps: Start-FileDownload https://downloads.sourceforge.net/project/opencpnplugins/opencpn_packaging_data/OpenCPN_buildwin.7z
#  - cmd: 7z x -y OpenCPN_buildwin.7z -oc:\project\dashboard_pi
  - cmake -T v140_xp ..

build_script:
  # - cmake --build . --config debug
  - cmake --build . --target package --config release

artifacts:
  - path: 'build\*.exe'
    name: installer

deploy:
  description: 'release created by AppVeyor CI'
  provider: GitHub
  auth_token:
    secure: TlzWWbLC1CFCpSHQIFCIxdZhRQjLRZq+ylg578A6I/MH9UxtKcbi5IdnZf8C1/wY
  artifact: installer
  draft: true
  prerelease: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true # deploy on tag push only
    configuration: Release  # Debug contains non-redist MS DLLs
